config/routes.rb
Rails.application.routes.draw do
  get 'dashboard',to: 'projects#index'
  get 'projects/new', to: 'projects#new'
  post 'projects', to: 'projects#create'
  delete 'projects/:id', to: 'projects#destroy', as: 'destroy_project'
  root 'projects#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
    validates :status, presence: true
    enum status: [:proposal, :progress, :finished]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  http_basic_authenticate_with name: "desafiovamoscontodo", password: "tupassword", only: :index

  def index
    @projects = Project.all
    if params[:status] and params[:status] != 'all'
      @projects = @projects.where(status: params[:status])
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to dashboard_path
    else
      render 'new'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      redirect_to dashboard_path
    end
  end

  private
  def project_params
    params.require(:project).permit(:name, :description, :started_at, :ended_at, :status) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project Management</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-warning">
  <a class="navbar-brand">Project Management</a>
    <div class="navbar-nav">
        <a><%= link_to 'Create Project', projects_new_path%></a>
        <a><%= link_to 'Dashboard', dashboard_path%></a>
    </div>
  </nav>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/index.html.erb
<h1 class= "text-center">Projects Index</h1>
<p class= "text-center">Here we can check all the projects created and their progress until they are finished</p>


<%= form_with url: "/dashboard", method: :get, class: "form-inline" do |form| %>
 <div class="form-group mx-sm-3 mb-2">
  <%= form.label :query, "Filter projects: " %>
   <%= form.select :status, [["All", :all], ["Proposal", :proposal], ["Progress", :progress], ["Finished", :finished]], {selected: params[:status]},class:'form-control' %>
   </div>
  <%= form.submit "Search", class: 'btn btn-warning mb-2' %>
<% end %>
<br>

<table class="table bg-warning">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Started</th>
      <th scope="col">Finished</th>
      <th scope="col">Status</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <% @projects.each do |project| %>
      <th><%= project.name %></th>
      <td><%= project.description %></td>
      <td><%= project.started_at %></td>
      <td><%= project.ended_at%></td>
      <td><%= project.status%></td>
      <td><%= link_to 'Delete', destroy_project_path(project), method: :delete%></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1 class="text-center">Project Form</h1>

<% if @project.errors.any? %>
    <div id="error_explanation">
        <h2>
            <%= pluralize(@project.errors.count, "error") %> prohibited this post from being saved:</h2>
            <ul>
                <% @project.errors.full_messages.each do |msg|%>
                    <li><%= msg %></li>
                <% end %>
            </ul>
    </div>
<% end %>

<%= form_with model: @project do |form|%>
   <%= form.text_field :name, class:'form-control', placeholder: 'Name'%>
   <%= form.text_area :description, size: '60x10', class:'form-control', placeholder: 'Description' %>
   <%= form.date_field :started_at, class:'form-control' %>
   <%= form.date_field :ended_at, class:'form-control' %>
   <%= form.select :status, [["Proposal", :proposal],["Progress", :progress],["Finished", :finished]],{}, class:'form-control' %>
   <br>
   <%= form.submit 'Send', class: 'btn btn-warning' %>
<% end %>